jornal_interno/jornal_interno/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plataforma.urls')),
]

jornal_interno/plataforma/urls.py
from django.urls import path
from . import views

app_name = 'plataforma'
urlpatterns = [

    path('homejornal', views.homejornal, name='homejornal'),
    path('cadastronoticia/<int:edicao_id>/', views.CadastroNoticia.as_view(), name='cadastronoticia'),
    path('edicao/<int:edicao_id>/', views.detailedicao, name='detailedicao'),
    path('edicao/noticia/<int:noticia_id>/', views.detailnoticia, name='detailnoticia'),

    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logoutView, name='logout'),

    path('cadastroedicao/', views.CadastroEdicao.as_view(), name='cadastroedicao'),
    path('cadastrocomentario/<int:noticia_id>/', views.CadastroComentario.as_view(), name='cadastrocomentario'),
    path('cadastrocolunista/', views.CadastroColunista.as_view(),name='cadastrocolunista'),
]

jornal_interno/plataforma/models.py
from django.db import models
from django.contrib.auth.models import User


class Colunista(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=15)

    class Meta:
        verbose_name_plural = 'Colunistas'

    def __str__(self):
        return f"Nome: {self.user.username} - CPF: {self.cpf} "    

class Edicao(models.Model):
    colunista = models.ForeignKey(Colunista, on_delete=models.CASCADE)
    texto = models.CharField(max_length=200)
    data_pub = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Edições'

    def __str__(self):
            return ("{0} - {1}").format(self.id, self.texto)

class Noticia(models.Model):
    colunista = models.ForeignKey(Colunista, on_delete=models.CASCADE)
    texto = models.CharField(max_length=500)
    edicao = models.ForeignKey(Edicao, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Noticias'

    def __str__(self):
            return ("{0} - {1}").format(self.edicao.texto, self.texto)

class Comentario(models.Model):
    colunista = models.ForeignKey(Colunista, on_delete=models.CASCADE)
    texto = models.CharField(max_length=200)
    noticia = models.ForeignKey(Noticia, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Comentarios'  

    def __str__(self):
            return ("{0} - {1}").format(self.noticia.texto, self.texto)   

jornal_interno/plataforma/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Colunista, Edicao,Noticia,Comentario
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views import View
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User


class Login(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'plataforma/login.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        senha = request.POST['senha']
        user = authenticate(request, username=username, password=senha)
        if user is not None:
            login(request, user)
            if hasattr(request.user, 'colunista'):
                return HttpResponseRedirect(reverse('plataforma:homejornal'))
        else:
            erro = 'Email e senha inválidas!'
            return render(request, 'plataforma/login.html', {'erro': erro})

def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('plataforma:homejornal'))

class CadastroColunista(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'plataforma/cadastrocolunista.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        cpf = request.POST['cpf']
        senha = request.POST['senha']
        if username and cpf and senha:
            user = User.objects.create_user(
                username=username, password=senha)
            Colunista.objects.create(user=user, cpf=cpf)
            return HttpResponseRedirect(reverse('plataforma:login'))
        else:
            erro = 'Informe corretamente os parâmetros necessários!'
            return render(request, 'plataforma/cadastrocolunista.html', {'erro': erro})

@method_decorator(login_required(login_url="/login/"), name='dispatch')
class CadastroEdicao(View):
    def get(self, request, *args, **kwargs):
        colunista = request.user.colunista
        contexto = {'colunista': colunista}
        return render(request, 'plataforma/cadastraredicao.html', contexto)

    def post(self, request, *args, **kwargs):
        texto = request.POST['texto']

        if texto:
            if hasattr(request.user, 'colunista'):
                edicao = Edicao(colunista=request.user.colunista, texto = texto)
                edicao.save()
                return HttpResponseRedirect(reverse('plataforma:homejornal'))
            else:
                erro = 'Usuario não logado!'
                return render(request, 'plataforma/login.html', {'erro': erro})
        else:
            erro = 'Informe corretamente os parâmetros necessários!'
            return render(request, 'plataforma/cadastraredicao.html', {'erro': erro})

@method_decorator(login_required(login_url="/login/"), name='dispatch')
class CadastroNoticia(View):
    def get(self, request, edicao_id, *args, **kwargs):
        colunista = request.user.colunista
        edicao = get_object_or_404(Edicao, pk=edicao_id)
        contexto = {'colunista': colunista,'edicao': edicao}
        return render(request, 'plataforma/cadastrarnoticia.html', contexto)

    def post(self, request, edicao_id, *args, **kwargs):
        texto = request.POST['texto']
        edicao = get_object_or_404(Edicao, pk=edicao_id)

        if texto:
            if hasattr(request.user, 'colunista'):
                noticia = Noticia(colunista=request.user.colunista, texto = texto, edicao = edicao)
                noticia.save()
                return HttpResponseRedirect(reverse('plataforma:detailedicao', args=(edicao_id,)))
            else:
                erro = 'Usuario não logado!'
                return render(request, 'plataforma/login', {'erro': erro})
        else:
            erro = 'Informe corretamente os parâmetros necessários!'
            return render(request, 'plataforma/cadastrarnoticia.html', {'erro': erro})

@method_decorator(login_required(login_url="/login/"), name='dispatch')
class CadastroComentario(View):
    def get(self, request, noticia_id, *args, **kwargs):
        colunista = request.user.colunista
        noticia = get_object_or_404(Noticia, pk=noticia_id)
        contexto = {'colunista': colunista, 'noticia': noticia}
        return render(request, 'plataforma/cadastrarcomentario.html', contexto)

    def post(self, request, noticia_id, *args, **kwargs):
        texto = request.POST['texto']
        noticia = get_object_or_404(Noticia, pk=noticia_id)
    
        if texto:
            if hasattr(request.user, 'colunista'):
                comentario = Comentario(colunista=request.user.colunista, texto = texto, noticia = noticia)
                comentario.save()
                return HttpResponseRedirect(reverse('plataforma:detailnoticia', args=(noticia_id,)))
            else:
                erro = 'Usuario não logado!'
                return render(request, 'plataforma/login', {'erro': erro})
        else:
            erro = 'Informe corretamente os parâmetros necessários!'
            return render(request, 'plataforma/cadastrarcomentario.html', {'erro': erro})
    

def homejornal(request):
    edicao_list = Edicao.objects.order_by('-data_pub')[:5]
    context = {'edicao_list': edicao_list}
    return render(request,'plataforma/homejornal.html', context)

def detailedicao(request, edicao_id):
    edicao = get_object_or_404(Edicao, pk=edicao_id)
    return render(request,'plataforma/detailedicao.html',{'edicao': edicao})

def detailnoticia(request, noticia_id):
    noticia = get_object_or_404(Noticia, pk=noticia_id)
    return render(request,'plataforma/detailnoticia.html',{'noticia': noticia})

jornal_interno/plataforma/templates/plataforma/cadastrarcomentario.html
{% block title %}Login{% endblock %}
{% block content %}
<body>
    <main>
        <p>Cadastre um comentario na noticia: {{noticia.texto}}</p>
        <form action="{% url 'plataforma:cadastrocomentario' noticia.id %}" method="POST" id="cadastrocomentario">
            {% csrf_token %}
            <label for="texto">Comentario:</label>
            <input type="texto" name="texto" id="texto" placeholder="Digite seu comentario"  required>
            <input type="submit" value="Comentar">
            <input type="hidden" name="next" value="{{ next }}">
        </form>
    </main>
</body>
{% endblock %}

jornal_interno/plataforma/templates/plataforma/cadastraredicao.html
{% block title %}Login{% endblock %}
{% block content %}
<body>
    <main>
        <p>Cadastre uma nova edição!</p>
        <form action="{% url 'plataforma:cadastroedicao' %}" method="POST" id="cadastroedicao">
            {% csrf_token %}
            <label for="texto">Texto</label>
            <input type="texto" name="texto" id="texto" placeholder="Digite o texto da edição"  required>
            <input type="submit" value="Cadastrar edição">
            <input type="hidden" name="next" value="{{ next }}">
        </form>
    </main>
</body>
{% endblock %}

jornal_interno/plataforma/templates/plataforma/cadastrarnoticia.html
{% block title %}Login{% endblock %}
{% block content %}
<body>
    <main>
        <p>Cadastre uma noticia na edição {{edicao.texto}}</p>
        <form action="{% url 'plataforma:cadastronoticia' edicao.id %}" method="POST" id="cadastronoticia">
            {% csrf_token %}
            <label for="texto">Texto da noticia</label>
            <input type="texto" name="texto" id="texto" placeholder="Digite o texto da noticia"  required>
            <input type="submit" value="Cadastrar noticia">
            <input type="hidden" name="next" value="{{ next }}">
        </form>
    </main>
</body>
{% endblock %}

jornal_interno/plataforma/templates/plataforma/cadastrocolunista.html
{% block title %}Login{% endblock %}
{% block content %}
<body>
    <main>
        <p>Crie seu cadastro!</p>
        <form action="{% url 'plataforma:cadastrocolunista' %}" method="POST" id="cadastrocolunista">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="username" name="username" id="username" placeholder="Digite seu username"  required>
            <label for="senha">Senha</label>
            <input type="password" name="senha" id="senha" placeholder="Digite sua senha"  required>
            <label for="cpf">CPF</label>
            <input type="cpf" name="cpf" id="cpf" placeholder="Digite seu cpf"  required>
            <input type="submit" value="Cadastrar-se">
            <input type="hidden" name="next" value="{{ next }}">
        </form>
    </main>
</body>
{% endblock %}

jornal_interno/plataforma/templates/plataforma/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div class="center">
        {% if request.user.colunista %}
            <li><a href="{% url 'plataforma:logout' %}">Logout</a></li>
        {% endif %}
        <a href= "{% url 'plataforma:index' %}">Pagina principal</a>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <h1><strong>Noticias da {{edicao.texto}}:</strong></h1>
        {% for noticia in edicao.noticia_set.all %}
            <li><a href="{% url 'plataforma:detailnoticia' noticia.id %}">{{ noticia.texto }}</li>
        {% endfor %}
    </div>
    {% if request.user.colunista %}
        <li><a href="{% url 'plataforma:cadastronoticia' edicao.id %}">Cadastrar nova noticia nesta edição</a></li>
    {% else %}
        <li><a href="{% url 'plataforma:login'%}">Faça login para cadastrar uma noticia</a></li>
    {% endif %}
</body>
</html>

jornal_interno/plataforma/templates/plataforma/detailedicao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div class="center">
        {% if request.user.colunista %}
            <li><a href="{% url 'plataforma:logout' %}">Logout</a></li>
        {% endif %}
        <li><a href= "{% url 'plataforma:homejornal' %}">Pagina principal</a></li>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <h1><strong>Noticias da edição {{edicao.texto}}:</strong></h1>
        {% for noticia in edicao.noticia_set.all %}
            <li><a href="{% url 'plataforma:detailnoticia' noticia.id %}">{{ noticia.texto }}</li>
        {% endfor %}
    </div>
    <br>
    {% if request.user.colunista %}
        <li><a href="{% url 'plataforma:cadastronoticia' edicao.id %}">Cadastrar nova noticia nesta edição</a></li>
    {% else %}
        <li><a href="{% url 'plataforma:login'%}">Faça login para cadastrar uma noticia</a></li>
    {% endif %}
</body>
</html>

jornal_interno/plataforma/templates/plataforma/detailnoticia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div class="center">
        {% if request.user.colunista %}
            <li><a href="{% url 'plataforma:logout' %}">Logout</a></li>
        {% endif %}
        <li><a href= "{% url 'plataforma:homejornal' %}">Pagina principal</a></li>
        <li><a href= {% url 'plataforma:detailedicao' noticia.edicao.id %}>Voltar</a></li>
        <h1>{{ noticia.texto }}</h1>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <u><strong>COMENTARIOS:</strong></u>
        {% for comentario in noticia.comentario_set.all %}
            <li>{{ comentario.texto }}</li>
        {% endfor %}
    </div>
    <br>
    {% if request.user.colunista %}
        <li><a href="{% url 'plataforma:cadastrocomentario' noticia.id %}">Cadastrar novo comentario</a></li>
    {% else %}
        <li><a href="{% url 'plataforma:login'%}">Faça login para cadastrar um comentario</a></li>
    {% endif %}
</body>
</html>

jornal_interno/plataforma/templates/plataforma/homejornal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div class="center">
        {% if request.user.colunista %}
            <li><a href="{% url 'plataforma:logout' %}">Logout</a></li>
            <li><a href="{% url 'plataforma:cadastroedicao' %}">Cadastrar nova edição</a></li>
        {% else %}
            <li><a href="{% url 'plataforma:login' %}">Login</a></li>
        {% endif %}
        <h1>EDIÇÕES:</h1>
        {% if edicao_list %}
            <ul>
            {% for edicao in edicao_list %}
                <li><a href="{% url 'plataforma:detailedicao' edicao.id %}">{{ edicao.texto }}</a></li>
            {% endfor %}
            </ul>
            <h1>NOTICIAS RECENTES:</h1>
            <ul>
            {% for edicao in edicao_list %}
                {% for noticia in edicao.noticia_set.all %}
                    <li><a href="{% url 'plataforma:detailnoticia' noticia.id %}">{{ noticia.texto }}</a></li>
                {% endfor %}
            {% endfor %}
            </ul>
        {% else %}
            <p>Nenhuma edicao disponível</p>
        {% endif %}
        <a href="admin/">Admin</a>
    </div>
</body>
</html>

jornal_interno/plataforma/templates/plataforma/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div class="center">
        {% if request.user.colunista %}
            <li><a href="{% url 'plataforma:logout' %}">Logout</a></li>
            <li><a href="{% url 'plataforma:cadastroedicao' %}">Cadastrar nova edição</a></li>
        {% else %}
            <li><a href="{% url 'plataforma:login' %}">Login</a></li>
        {% endif %}
        <h1>EDIÇÕES:</h1>
        {% if edicao_list %}
            <ul>
            {% for edicao in edicao_list %}
                <li><a href="{% url 'plataforma:detail' edicao.id %}">{{ edicao.texto }}</a></li>
            {% endfor %}
            </ul>
            <h1>NOTICIAS RECENTES:</h1>
            <ul>
            {% for edicao in edicao_list %}
                {% for noticia in edicao.noticia_set.all %}
                    <li><a href="{% url 'plataforma:detailnoticia' noticia.id %}">{{ noticia.texto }}</a></li>
                {% endfor %}
            {% endfor %}
            </ul>
        {% else %}
            <p>Nenhuma edicao disponível</p>
        {% endif %}
        <a href="admin/">Admin</a>
    </div>
</body>
</html>

jornal_interno/plataforma/templates/plataforma/login.html
{% block title %}Login{% endblock %}
{% block content %}
<body>
    <main>
        <p>Faça login na sua conta</p>
        <form action="{% url 'plataforma:login' %}" method="POST" id="login">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="username" name="username" id="username" placeholder="Digite seu username"  required>
            <label for="senha">Senha</label>
            <input type="password" name="senha" id="senha" placeholder="Digite sua senha"  required>
            <input type="submit" value="Entrar">
            <input type="hidden" name="next" value="{{ next }}">               
        </form>
        <p>Não tem uma conta? <a href="{%url 'plataforma:cadastrocolunista'%}">Cadastrar-se</a></p>
    </main>
</body>
{% endblock %}